CREATE DATABASE ${MYSQL_DB_NAME} ;
SHOW DATABASES ;

CREATE USER ${MYSQL_DB_USER}@localhost IDENTIFIED BY ${MYSQL_DB_PASS};

GRANT USAGE ON *.* TO ${MYSQL_DB_USER}@localhost IDENTIFIED BY ${MYSQL_DB_PASS};

GRANT ALL PRIVILEGES ON ${MYSQL_DB_NAME}.* TO ${MYSQL_DB_USER}@localhost IDENTIFIED BY ${MYSQL_DB_PASS};

FLUSH PRIVILEGES;
