version: "3.6"

  #volumes:
  #wordpress:

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASS=${MYSQL_DB_PASS}
    volumes:
      - maria-dataa:/var/lib/mysql
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    build: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-dataa:/var/www/html
    networks:
      - my_network
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: wordpress
    environment:
      - DB_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WP_DB_NAME=${MYSQL_DB_NAME}
      - WP_DB_USER=${MYSQL_DB_USER}
      - WP_DB_PASS=${MYSQL_DB_PASS}
    depends_on:
      - mariadb
    links:
      - mariadb
    volumes:
      - wp-dataa:/var/www/html
    networks:
      - my_network
  
networks:
  my_network:

volumes:
  maria-dataa:
    driver: local
    driver_opts:
      o: bind
      type: "nfs"
      device: "/home/hrazanam/data/maria-data"
  wp-dataa:
    driver: local
    driver_opts:
      o: bind
      type: "nfs"
      device: "/home/hrazanam/data/wp-data"
