version: "3.3"

  #volumes:
  #wordpress:

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME};
      - MYSQL_DB_USER=${MYSQL_DB_USER};
      - MYSQL_DB_PASS=${MYSQL_DB_PASS};
    ports:
      - "3306:3306"
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    build: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - my_network
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: wordpress
    environment:
      - DB_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WP_DB_NAME=${MYSQL_DB_NAME}
      - WP_DB_USER=${MYSQL_DB_USER}
      - WP_DB_PASS=${MYSQL_DB_PASS}
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    links:
      - mariadb
    networks:
      - my_network
  
networks:
  my_network:

