service mysql start
echo "$MYSQL_DB_NAME $MYSQL_DB_USER et $MYSQL_DB_PASS"
mysql -u root -proot  << EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_DB_NAME ;
SHOW DATABASES ;
USE $MYSQL_DB_NAME ;
CREATE USER '$MYSQL_DB_USER'@'wordpress.inception_my_network' IDENTIFIED BY '$MYSQL_DB_PASS';
SELECT user FROM user
GRANT ALL PRIVILEGES ON '$MYSQL_DB_NAME'.* TO '$MYSQL_DB_USER'@'wordpress.inception_my_network' IDENTIFIED BY '$MYSQL_DB_PASS';
FLUSH PRIVILEGES;
EOF
